language: go

dist: xenial

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

go:
  - '1.13.1'

matrix:
  allow_failures:
    - go: tip

services:
  - docker

before_install:
  - sudo apt-get update || true
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;
  - go get github.com/mattn/goveralls

addons:
  apt:
    packages:
    - devscripts
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make
    - dh-golang
    - upx-ucl
    - python
    - python-pip

install:
  - sudo pip install --upgrade pip
  - pip install --upgrade --user jsonschema
  - pip install --upgrade --user awscli

script:
  - echo "$TRAVIS_BUILD_NUMBER" > RELEASE
  - make test
