version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=~#UPROJECT#~
      - MYSQL_DATABASE=~#UPROJECT#~
      - MYSQL_USER=~#UPROJECT#~
      - MYSQL_PASSWORD=~#UPROJECT#~
    ports:
      - "9306:3306"
    volumes:
      - ./resources/test/mysql:/docker-entrypoint-initdb.d

  consul:
    image: "progrium/consul:latest"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect=1"

  ~#PROJECT#~:
    build:
      context: .
      dockerfile: ~#PROJECT#~.test.Dockerfile
    depends_on:
      - "db"
      - "consul"
    ports:
      - "8017:8017"
    environment:
      - ~#UPROJECT#~_REMOTECONFIGPROVIDER=consul
      - ~#UPROJECT#~_REMOTECONFIGENDPOINT="consul:8500"
      - ~#UPROJECT#~_REMOTECONFIGPATH=/config/~#PROJECT#~
      - ~#UPROJECT#~_REMOTECONFIGSECRETKEYRING=""
    stdin_open: true
    tty: true



    
